### ISSUE TITLE
Issues with MODx 2.5.6

### ISSUE THREAD

**Issue by michaelc0302** [minagerges/MODX-GoogleAuthenticatorX#17]
I've been using MODX-GoogleAuthenticatorX for a while now and it has been working very well. However, earlier today I had to upgrade MODx to 2.5.6-pl, so I went into settings and disabled the authentication, ran the upgrade (which went fine), logged in and re-enabled the authentication.

I now cant log in at all. I keep getting the "Invalid authentication key." error.

I signed into the database remotely and changed the gax_disabled setting to 1, in the hope of being able to log in but that didn't work either and the Authentication Key field is still visible on the login form and I have verified that the setting is definitely 1.

**Comment by minagerges** [comment]
Hi,

The issue is caused by Modx installation generating new identifier which is
used for encryption.

You got issued a new token by GAx, and you still can't login because
settings are cached by Modx. Clear the cache folder while 2FA is disabled
in DB, and you will be able to login. Update your token via the new Qrcode
and you are good to go.

Kind regards,
Mina Gerges

**Comment by michaelc0302** [comment]
Hi Mina,
That worked absolutely perfectly. Thank you for your help with this. 
Best regards,
Michael

**Comment by girs1982** [comment]
how it use in user login form?
