### ISSUE TITLE
several literal issues + default URL embeds the manager login URL or a manager alias. Better to limit it to eg. the site

### ISSUE THREAD

**Issue by XStreamke** [minagerges/MODX-GoogleAuthenticatorX#20]
Several times the code makes calls to the log. However as of PHP greater than v7.3.x this will result in errors.
Solution is to have the debug, warn info and error statements all set as a literal 'debug','warn','info','error'
Provide error log: PHP warning: Use of undefined constant warn - assumed 'warn' (this will throw an Error in a future version of PHP)

If you wish to delete the manage URL from the URI, you have to alter both the PHP class and the snippet GAxUserQRCode

**Comment by minagerges** [comment]
@XStreamke thank  you for reporting. 
_Each reported issue should be in a separate issue in tracker._
The log warning commit above.

With regarding to the URI exposing manager URL, I see in snippet "GAxUserQRCode" that it uses `$modx->getOption('site_url')`

So front-end users get site_url based URI while back-end user get manager based URI. Have you tested with otherwise results!? If you face different behavior please report in new issue.

**Comment by XStreamke** [comment]
Mina, 

I've altered the code, but I was using a non-manager user and a manager user. But I was always using the manager login page back then. Afterwards I've altered the code so that I get something different, that suits more my presentation in Google Authenticator. And that works fine using the manager URL and the custom login page. 

Regards, 
Kevin

**Comment by sdrenth** [comment]
@minagerges If you could make a new release where this fix is included in that would be great! :)
